---
title: "Equipe organizadora"
title-block-banner: true
---

## Comissão Organizadora

### Agnes de Oliveira Franco

-   Discente de doutorado no PROCAM
-   Orientada por: Prof. Dr. Pedro Luiz Côrtes
-   Email: [agnesfranco\@usp.br](mailto:agnesfranco@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/8679823249124616>

> Jornalista especializada em Políticas Públicas, mestre em Política Trabalhista (ciências políticas) e Globalização (economia) pela Universidade de Kassel e Universidade de Economia e Direito de Berlim, via Universidade Global do Trabalho (https://global-labour-university.org/). Doutoranda em Ciências Ambientais (PROCAM-USP). Pesquisa Transição Justa, negacionismo e desinformação climática e ambiental. Trabalha com diversas vertentes da agenda socioambiental, área em que atua há mais de vinte anos. Tem boa experiência com formação, relações internacionais, gerenciamento e comunicação.

### Anelise Gomes da Silva

-   Egressa do PROCAM
-   Orientada por: Prof. Dr. Paulo Sinisgalli
-   Currículo Lattes: <http://lattes.cnpq.br/9933001298697288>

> Doutora em Ciência Ambiental pelo Instituto de Energia e Ambiente (IEE) da Universidade de São Paulo (USP), com estágio de pesquisa na Faculdade de Ciências e Tecnologia da Universidade NOVA de Lisboa (Portugal). Mestre em Ciências da Engenharia Ambiental pelo Programa de Pós-Graduação em Ciências da Engenharia Ambiental (PPG-SEA/USP) e graduada em Ciências Sociais, com ênfase em Ciência Política e Sociologia pela Universidade Federal de São Carlos (UFSCar). Atua na interface entre políticas públicas e meio ambiente, com ênfase em pesquisas aplicadas à governança ambiental, instrumentos econômicos de política ambiental e valoração econômica dos serviços ecossistêmicos. As áreas de interesse incluem: Políticas Públicas; Processos Decisórios; Avaliação de Políticas; Governança; Instrumentos de Política Ambiental; Valoração Econômica Ambiental; Economia do Meio Ambiente.

### Beatriz Milz

-   Egressa do PROCAM
-   Orientada por: Prof. Dr. Pedro Roberto Jacobi
-   Email: [milz.bea\@gmail.com](mailto:milz.bea@gmail.com)
-   Currículo Lattes: <http://lattes.cnpq.br/5150665880581477>

> Doutora no Programa de Pós-Graduação em Ciência Ambiental, no Instituto de Energia e Ambiente - Universidade de São Paulo (PROCAM/IEE/USP), com bolsa FAPESP no período entre 05/2019 à 01/2022 (18/23771-6). Mestre em Ciências (2018) pelo Programa de Pós-Graduação em Análise Ambiental Integrada - Universidade Federal de São Paulo (UNIFESP). Bacharel em Gestão Ambiental (2015) pela Escola de Artes, Ciências e Humanidades da Universidade de São Paulo (EACH/USP). Faz parte da equipe da Secretaria Executiva da Revista Ambiente Sociedade (2018-atualmente). Editora associada na ROpenSci (Software peer review editor). Participou como pesquisadora no Projeto Temático FAPESP: Governança Ambiental na Macrometrópole Paulista face à variabilidade climática (Processo: 2015/03804-9). É co-organizadora da comunidade R-Ladies São Paulo desde outubro de 2018.

### Gabriela Simões Garcia

-   Discente de doutorado no PROCAM
-   Orientada por: Prof. Dr. Paulo Sinisgalli
-   Email: [gabriela.garcia\@usp.br](mailto:gabriela.garcia@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/3944109123977025>

> Doutoranda no Programa de Pós-Graduação em Ciência Ambiental (PROCAM, IEE-USP). Mestre em Design pela Universitat Politècnica de Catalunya (UPC, 2019). Graduada em Arquitetura e Urbanismo pela Universidade de São Paulo (FAU-USP, 2012), com intercâmbio na Universidad Politécnica de Madrid (ETSAM-UPM, 2011). Desenvolve projetos e pesquisas que abordam tópicos relacionados a design ecológico, regeneração urbana e rural, design participativo, fabricação digital, cultura material e compartilhamento de conhecimentos.

<!-- Henrique: nome completo e demais informações a completar -->

### Isabela Carmo Cavaco

-   Discente de doutorado no PROCAM
-   Orientada por: Prof. Dr. Pedro Roberto Jacobi
-   Email: [isabcvc\@usp.br](mailto:isabcvc@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/0124986877086141>

> Bacharel em Gestão Ambiental pela EACH/USP (2023), mestre (2025) e doutoranda em Ciência Ambiental pelo IEE/USP. Pesquisa os significados da justiça climática desde 2022, com foco em populações vulnerabilizadas no Brasil, racismo ambiental, e interseccionalidade de raça, gênero e classe. Realizou intercâmbio de 3 meses nos Países Baixos, na Universidade de Groningen, onde estudou o ativismo jovem por justiça climática. Atualmente pesquisa planejamento territorial e recuperação de áreas de preservação permanente na zona sul da cidade de São Paulo, sob a lente de justiça climática.

### Lucas Monteiro de Carvalho Silva

-   Discente de doutorado no PROCAM
-   Orientado por: Prof. Dr. Maurício Lamano Ferreira
-   Email: [lucas.mdecs\@usp.br](mailto:lucas.mdecs@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/0456155611769985>

> Bacharel Interdisciplinar em Ciência e Tecnologia com ênfase no mar (BICT-Mar) e Mestre em Ciências pela Universidade Federal de São Paulo (UNIFESP). Atuou como Analista Ambiental no projeto de pesquisa Canta Galo da Universidade de São Paulo (USP) e na empresa GreenWaveClean. É pesquisador colaborador do Centro de Capacitação e Pesquisa em Meio Ambiente (CEPEMA - POLI -USP) e do Laboratório de Florestas, Clima e CIdades (LFC) da Escola de Engenharia de Lorena (EEL/USP). Tem experiência na área de Educação Ambiental, Ensino básico de ciências, Ecotoxicologia, Gerenciamento de áreas contaminadas (GAC), Ciências Ambientais e Ciências do Mar. Atualmente, é bolsista FAPESP e doutorando no Programa de Pós Graduação em Ciência Ambiental do Instituto de Energia e Ambiente da Universidade de São Paulo (IEE/USP) com pesquisa na área de Arborização Urbana, com base na regra 3-30-300, e a sua relação com a poluição atmosférica.

### Lucas Teixeira

Em breve.

### Luiz Guilherme Ferreira Pires

-   Discente de mestrado no PROCAM
-   Orientado por: Profa. Dra. Sylmara Lopes Francelino Gonçalves Dias
-   Email: [luizguilhermeferreira\@usp.br](mailto:luizguilhermeferreira@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/8200771159880686>

> Pesquisador bolsista FAPESP e mestrando em Ciência Ambiental pelo Instituto de Energia e Ambiente da Universidade de São Paulo (IEE/USP). Pesquisador colaborador no projeto FAPESP PPPP Coop Clima - São Vicente. Voluntário no Programa Adapta Keraciaba. Graduado em Gestão Ambiental pela Escola de Artes, Ciências e Humanidades (EACH/USP), com intercâmbio na Universidad de Córdoba (Colômbia). Atua em ensino, pesquisa e extensão nas áreas de justiça climática, adaptação climática, participação social em políticas públicas municipais ambientais e climáticas e educação para redução de riscos de desastres socioambientais.

### Marina Walder

-   Discente de doutorado no PROCAM
-   Orientada por: Prof. Dr. Eduardo de Lima Caldas
-   Email: [marinaawg07\@usp.br](mailto:marinaawg07@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/4034067826741802>

> Jornalista, mestre em Ciências pelo Programa de Pós-Graduação em Sustentabilidade na EACH, doutoranda em Ciências Ambientais pelo Programa de Ciências Ambientais do Instituto de Energia e Ambiente da USP. Atua com consultoria e comunicação em projetos de impacto socioambiental, com experiência em iniciativas desenvolvidas por organizações nacionais e internacionais.

### Pablo Sosa

-   Egresso do PROCAM
-   Email: [pablo.papito\@gmail.com](mailto:pablo.papito@gmail.com)
-   Currículo Lattes: <http://lattes.cnpq.br/8050433813858734>

> Bacharel em Gestão Ambiental,  mestre e doutor em Ciência Ambiental pela USP, desenvolve pesquisas em valoração de serviços ecossistêmicos e metodologias de valoração. Atuou por muitos anos em grandes empresas e consultorias internacionais na área de sustentabilidade corporativa e atualmente é pesquisador de pós doutorado, associado ao Instituto de Energia e Ambiente - IEE - da USP, dedicando-se à pesquisa sobre serviços ecossistêmicos de arborização urbana, em linha com estratégias e objetivos do PlaNAU (Plano nacional de Arborização urbana).

### Rafaela Carolina Pereira Campos

-   Discente de mestrado no PROCAM
-   Orientada por: Profa. Dra. Ana Paula Fracalanza
-   Email: [rafaelacampos\@usp.br](mailto:rafaelacampos@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/0237019254863684>

> Mestranda em Ciência Ambiental pelo Instituto de Energia e Ambiente da Universidade de São Paulo (IEE-USP), com projeto sobre comitê de bacia hidrográfica e gestão de risco de secas. Pesquisadora bolsista pela FAPESP. Participa como voluntária no projeto de extensão "Atuação da UFABC como Sociedade Civil no Comitê de Bacia Hidrográfica do Alto Tietê". Bacharela em Geografia pela Faculdade de Filosofia, Letras e Ciências Humanas (FFLCH-USP). Possui experiências de estágio em órgãos ambientais e de pesquisa nos níveis municipal e estadual. Interesses de pesquisa: governança da água, gestão de risco de desastres, políticas públicas ambientais e eventos hidroclimáticos extremos.

### Raul Chiwale Matateu

-   Discente de doutorado no PROCAM
-   Orientado por: Prof. Dr. Paulo Sinisgalli
-   Email: [raulmatateu\@usp.br](mailto:raulmatateu@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/8773490357115178>

> Doutorando em Ciência Ambiental (PROCAM, IEE-USP). Mestre em Conservação da Natureza (ISCED-Huambo). Graduado em Biologia (ISCED-Huambo). Docente Universitário, atuando na interface entre a Ecologia Urbana, Economia Ambiental e Tecnologia de Informação e Comunicação, com enfase na Valoração Econômica Ambiental.

### Rosana Maria de Macedo Borges

-   Discente de doutorado no PROCAM
-   Currículo Lattes: <http://lattes.cnpq.br/7463283021194161>

> Possui graduação em Direito pela Universidade de Mogi das Cruzes (2018), graduação em Farmácia pela Pontifícia Universidade Católica de Campinas (1985), mestrado em Engenharia Mineral pela Universidade de São Paulo (2003) e mestrado em Direito pela Pontifícia Universidade Católica de São Paulo (2022). Atualmente é professora assistente na Pós-Graduação em Direito Ambiental da Pontifícia Universidade Católica de São Paulo (COGEAE). Docente do IPOG - Instituto de Pós-Graduação e Graduação nos cursos de pós-graduação em Perícia Ambiental e Engenharia Sanitária desde 2013, docente da Escola Superior da CETESB e docente do SENAC - Serviço Nacional de Aprendizagem Comercial - SP nos cursos de pós-graduação em Perícia Ambiental, Gestão Ambiental e Direito Ambiental. Foi docente no curso de pós-graduação em Gestão Ambiental, entre 2010 e 2013, do Instituto Mauá de Tecnologia, no componente curricular Gerenciamento de Áreas Contaminadas. Especialista em Resíduos e Análises Químicas Ambientais pela JICA - Japan International Cooperation Agency (1992 e 1993). Trabalha na Agência Ambiental Paulista - CETESB desde 1985, tendo participado do desenvolvimento de metodologias analíticas e da implantação de um laboratório de caracterização de resíduos industriais. Trabalhou no Departamento de Áreas Contaminadas do órgão ambiental paulista entre 2001 e janeiro de 2019. Assessora da Diretoria de Controle e Licenciamento Ambiental da Companhia de Tecnologia de Saneamento Ambiental entre 2019 e 2021, trabalha atualmente com licenciamento ambiental. Tem experiência na área de Ciências Ambientais, atuando principalmente nos seguintes temas: licenciamento, áreas contaminadas, risco e valoração de danos. Membro das câmaras técnicas ambientais de petróleo e derivados, áreas contaminadas e conciliação ambiental na CETESB desde 2019.

### Tainá Ângela Vedovello Bimbati

-   Discente de doutorado no PROCAM
-   Orientada por: Profa. Dra. Sylmara Francelino Lopes Gonçalves-Dias
-   Email: [tainabimbati\@usp.br](mailto:tainabimbati@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/0417333466889749>

> Engenheira Ambiental pela Faculdade Municipal Prof. Franco Montoro (2013), Mestra em Engenharia Civil pelo Departamento de Saneamento e Ambiente da Faculdade de Engenharia Civil, Arquitetura e Urbanismo da Universidade Estadual de Campinas (FECFAU/UNICAMP) (2017) e Doutoranda pelo Programa de Pós-Graduação em Ciência Ambiental (PROCAM) do Instituto de Energia e Ambiente da Universidade de São Paulo (IEE-USP). Possui mais de 10 anos de experiência em consultoria e pesquisa em resíduos sólidos, coleta seletiva, logística reversa, inclusão de catadores de materiais recicláveis em ações de responsabilidade compartilhada e reciclabilidade.

### Yuki Tako

-   Discente de doutorado no PROCAM
-   Orientada por: Prof. Dr. Pedro Torres
-   Email: [yukitako\@usp.br](mailto:yukitako@usp.br)
-   Currículo Lattes: <http://lattes.cnpq.br/6864276707993330>

> Bióloga pela Universidade Federal do Estado do Rio de Janeiro (UNIRIO), especialista em Meio Ambiente e Sustentabilidade pela Fundação Getulio Vargas (FGV) e mestra em Ciências pelo Programa de Pós-Graduação em Sustentabilidade da EACH-USP. Doutoranda pelo Programa de Pós-Graduação em Ciência Ambiental do Instituto de Energia e Ambiente da USP (PROCAM/IEE-USP). É servidora técnica na Universidade do Estado do Rio de Janeiro (UERJ) há mais de dez anos. Pesquisa justiça climática e adaptação climática, com foco em adaptação ao calor extremo em territórios vulnerabilizados.

## Comitê Científico

### Em breve!
