---
title: "Sobre o SICAM"
title-block-banner: true
---

O Simpósio Interdisciplinar de Ciência Ambiental (SICAM) é um evento organizado pelo [**Programa de Pós-Graduação em Ciência Ambiental (PROCAM)**](https://procam.iee.usp.br/pt/) do [Instituto de Energia e Ambiente da USP](http://www.iee.usp.br/?q=pt-br), com o objetivo de promover a integração das diversas frentes que regem a Ciência Ambiental e também dos diversos profissionais que atuam nesta área do conhecimento.

O SICAM já teve 5 [edições anteriores](edicoes-anteriores.qmd). Este ano, de 21 a 23 de outubro de 2026, será a sexta edição do Simpósio Interdisciplinar de Ciência Ambiental, o VI SICAM, cujo tema principal será: **“A Integridade da Informação e a Ciência Ambiental”**. Além disso, contará com mesas redondas, palestras e apresentação de trabalhos.

O VI SICAM é gratuito, em formato presencial, e encoraja a participação de toda a comunidade de pessoas interessadas no debate ambiental, em diferentes áreas de atuação, de dentro e de fora da universidade.

Contamos com a sua participação!

